"""
Tests for grimoire-setup.py — BMAD user configuration synchronisation tool.
"""

from __future__ import annotations

import importlib.util
import json
import sys
import textwrap
from pathlib import Path

import pytest

# ── Import du module (nom hyphenated) ─────────────────────────────────────────

_TOOL_PATH = Path(__file__).resolve().parent.parent / "framework" / "tools" / "grimoire-setup.py"
_spec = importlib.util.spec_from_file_location("grimoire_setup", _TOOL_PATH)
grimoire_setup = importlib.util.module_from_spec(_spec)
sys.modules["grimoire_setup"] = grimoire_setup
_spec.loader.exec_module(grimoire_setup)

UserConfig = grimoire_setup.UserConfig
ConfigDiff = grimoire_setup.ConfigDiff
SetupReport = grimoire_setup.SetupReport

# ── Fixtures ──────────────────────────────────────────────────────────────────

PROJECT_CONTEXT = textwrap.dedent("""\
    # Test project
    project:
      name: "my-project"
      description: "A test project"
      type: "webapp"
      stack: ["python"]

    user:
      name: "Alice"
      language: "English"
      document_language: "English"
      skill_level: "intermediate"

    memory:
      backend: "local"
    """)

BMM_CONFIG = textwrap.dedent("""\
    # BMM Module Configuration
    # Generated by BMAD installer
    # Version: 6.0.3

    project_name: old-project
    user_skill_level: expert
    planning_artifacts: "{project-root}/_bmad-output/planning-artifacts"
    implementation_artifacts: "{project-root}/_bmad-output/implementation-artifacts"
    project_knowledge: "{project-root}/docs"

    # Core Configuration Values
    user_name: OldUser
    communication_language: Français
    document_output_language: Français
    output_folder: "{project-root}/_bmad-output"
    """)

CORE_CONFIG = textwrap.dedent("""\
    # CORE Module Configuration
    # Generated by BMAD installer
    # Version: 6.0.3

    user_name: OldUser
    communication_language: Français
    document_output_language: Français
    output_folder: "{project-root}/_bmad-output"
    """)

CIS_CONFIG = textwrap.dedent("""\
    # CIS Module Configuration
    visual_tools:
      - mermaid

    # Core Configuration Values
    user_name: OldUser
    communication_language: Français
    document_output_language: Français
    output_folder: "{project-root}/_bmad-output"
    """)

COPILOT_INSTRUCTIONS = textwrap.dedent("""\
    <!-- BMAD:START -->
    # BMAD Method — Project Instructions

    ## Project Configuration

    - **Project**: old-project
    - **User**: OldUser
    - **Communication Language**: Français
    - **Document Output Language**: Français
    - **User Skill Level**: expert
    - **Output Folder**: {project-root}/_bmad-output

    ## BMAD Runtime Structure
    Some other content here.
    <!-- BMAD:END -->
    """)


@pytest.fixture()
def project_tree(tmp_path: Path) -> Path:
    """Create a minimal BMAD project tree for testing."""
    # project-context.yaml
    (tmp_path / "project-context.yaml").write_text(PROJECT_CONTEXT, encoding="utf-8")

    # _bmad module configs
    for module in ["bmm", "core", "cis", "tea", "bmb"]:
        d = tmp_path / "_bmad" / module
        d.mkdir(parents=True)
        if module == "bmm":
            (d / "config.yaml").write_text(BMM_CONFIG, encoding="utf-8")
        elif module == "core":
            (d / "config.yaml").write_text(CORE_CONFIG, encoding="utf-8")
        elif module == "cis":
            (d / "config.yaml").write_text(CIS_CONFIG, encoding="utf-8")
        else:
            # tea, bmb get the same as core
            (d / "config.yaml").write_text(CORE_CONFIG, encoding="utf-8")

    # _memory config
    mem = tmp_path / "_bmad" / "_memory"
    mem.mkdir(parents=True)
    (mem / "config.yaml").write_text(CORE_CONFIG, encoding="utf-8")

    # .github/copilot-instructions.md
    gh = tmp_path / ".github"
    gh.mkdir()
    (gh / "copilot-instructions.md").write_text(COPILOT_INSTRUCTIONS, encoding="utf-8")

    return tmp_path


@pytest.fixture()
def synced_tree(tmp_path: Path) -> Path:
    """Create a tree where all files are already in sync."""
    cfg = textwrap.dedent("""\
        project:
          name: "synced"

        user:
          name: "Bob"
          language: "Français"
          document_language: "Français"
          skill_level: "expert"
        """)
    (tmp_path / "project-context.yaml").write_text(cfg, encoding="utf-8")

    module_tpl = textwrap.dedent("""\
        user_name: Bob
        communication_language: Français
        document_output_language: Français
        output_folder: "{project-root}/_bmad-output"
        """)
    bmm_tpl = textwrap.dedent("""\
        project_name: synced
        user_skill_level: expert
        user_name: Bob
        communication_language: Français
        document_output_language: Français
        output_folder: "{project-root}/_bmad-output"
        """)

    for module in ["bmm", "core", "cis", "tea", "bmb"]:
        d = tmp_path / "_bmad" / module
        d.mkdir(parents=True)
        content = bmm_tpl if module == "bmm" else module_tpl
        (d / "config.yaml").write_text(content, encoding="utf-8")

    mem = tmp_path / "_bmad" / "_memory"
    mem.mkdir(parents=True)
    (mem / "config.yaml").write_text(module_tpl, encoding="utf-8")

    ci = textwrap.dedent("""\
        - **Project**: synced
        - **User**: Bob
        - **Communication Language**: Français
        - **Document Output Language**: Français
        - **User Skill Level**: expert
        """)
    gh = tmp_path / ".github"
    gh.mkdir()
    (gh / "copilot-instructions.md").write_text(ci, encoding="utf-8")

    return tmp_path


# ── Tests: _parse_yaml_value ──────────────────────────────────────────────────


class TestParseYamlValue:
    def test_simple_value(self):
        assert grimoire_setup._parse_yaml_value("name: Alice") == "Alice"

    def test_quoted_double(self):
        assert grimoire_setup._parse_yaml_value('name: "Alice"') == "Alice"

    def test_quoted_single(self):
        assert grimoire_setup._parse_yaml_value("name: 'Alice'") == "Alice"

    def test_value_with_colon(self):
        assert grimoire_setup._parse_yaml_value("url: http://localhost:8080") == "http://localhost:8080"

    def test_no_colon(self):
        assert grimoire_setup._parse_yaml_value("novalue") == ""


# ── Tests: load_project_context ───────────────────────────────────────────────


class TestLoadProjectContext:
    def test_loads_all_fields(self, project_tree: Path):
        cfg = grimoire_setup.load_project_context(project_tree / "project-context.yaml")
        assert cfg.project_name == "my-project"
        assert cfg.user_name == "Alice"
        assert cfg.communication_language == "English"
        assert cfg.document_output_language == "English"
        assert cfg.user_skill_level == "intermediate"

    def test_defaults_when_missing(self, tmp_path: Path):
        (tmp_path / "project-context.yaml").write_text("project:\n  name: test\n", encoding="utf-8")
        cfg = grimoire_setup.load_project_context(tmp_path / "project-context.yaml")
        assert cfg.project_name == "test"
        assert cfg.user_name == ""
        assert cfg.communication_language == "Français"

    def test_handles_comments_and_blanks(self, tmp_path: Path):
        content = textwrap.dedent("""\
            # Comment line
            project:
              name: "commented"

            # Another comment
            user:
              name: "Bob"
            """)
        (tmp_path / "project-context.yaml").write_text(content, encoding="utf-8")
        cfg = grimoire_setup.load_project_context(tmp_path / "project-context.yaml")
        assert cfg.project_name == "commented"
        assert cfg.user_name == "Bob"


# ── Tests: _read_yaml_key / _update_yaml_key ─────────────────────────────────


class TestYamlKeyHelpers:
    def test_read_existing_key(self):
        text = "user_name: Alice\nlang: FR"
        assert grimoire_setup._read_yaml_key(text, "user_name") == "Alice"
        assert grimoire_setup._read_yaml_key(text, "lang") == "FR"

    def test_read_missing_key(self):
        assert grimoire_setup._read_yaml_key("user_name: X", "missing") is None

    def test_read_quoted_value(self):
        assert grimoire_setup._read_yaml_key('user_name: "Alice"', "user_name") == "Alice"

    def test_update_preserves_prefix(self):
        text = "user_name: OldUser\nother: kept"
        updated = grimoire_setup._update_yaml_key(text, "user_name", "NewUser")
        assert "user_name: NewUser" in updated
        assert "other: kept" in updated

    def test_update_does_not_affect_other_keys(self):
        text = "user_name: X\nmy_user_name: Y"
        updated = grimoire_setup._update_yaml_key(text, "user_name", "Z")
        assert "user_name: Z" in updated
        assert "my_user_name: Y" in updated


# ── Tests: _update_copilot_instructions ───────────────────────────────────────


class TestUpdateCopilotInstructions:
    def test_updates_all_fields(self):
        cfg = UserConfig("proj", "Bob", "English", "English", "beginner")
        result = grimoire_setup._update_copilot_instructions(COPILOT_INSTRUCTIONS, cfg)
        assert "**Project**: proj" in result
        assert "**User**: Bob" in result
        assert "**Communication Language**: English" in result
        assert "**Document Output Language**: English" in result
        assert "**User Skill Level**: beginner" in result

    def test_preserves_surrounding_content(self):
        cfg = UserConfig("proj", "Bob", "EN", "EN", "expert")
        result = grimoire_setup._update_copilot_instructions(COPILOT_INSTRUCTIONS, cfg)
        assert "## BMAD Runtime Structure" in result
        assert "BMAD:START" in result

    def test_no_change_when_values_match(self):
        cfg = UserConfig("old-project", "OldUser", "Français", "Français", "expert")
        result = grimoire_setup._update_copilot_instructions(COPILOT_INSTRUCTIONS, cfg)
        assert result == COPILOT_INSTRUCTIONS


# ── Tests: check_config_file ─────────────────────────────────────────────────


class TestCheckConfigFile:
    def test_detects_diffs_bmm(self, project_tree: Path):
        cfg = UserConfig("my-project", "Alice", "English", "English", "intermediate")
        path = project_tree / "_bmad" / "bmm" / "config.yaml"
        diffs = grimoire_setup.check_config_file(path, cfg, "bmm")
        keys = {d.key for d in diffs}
        assert "user_name" in keys
        assert "communication_language" in keys
        assert "project_name" in keys
        assert "user_skill_level" in keys

    def test_detects_diffs_core(self, project_tree: Path):
        cfg = UserConfig("my-project", "Alice", "English", "English", "intermediate")
        path = project_tree / "_bmad" / "core" / "config.yaml"
        diffs = grimoire_setup.check_config_file(path, cfg, "core")
        keys = {d.key for d in diffs}
        assert "user_name" in keys
        assert "communication_language" in keys
        # core does NOT have project_name or user_skill_level
        assert "project_name" not in keys
        assert "user_skill_level" not in keys

    def test_no_diffs_when_synced(self, synced_tree: Path):
        cfg = UserConfig("synced", "Bob", "Français", "Français", "expert")
        for module in grimoire_setup.MODULE_CONFIGS:
            path = synced_tree / "_bmad" / module / "config.yaml"
            assert grimoire_setup.check_config_file(path, cfg, module) == []

    def test_missing_file_returns_empty(self, tmp_path: Path):
        cfg = UserConfig("x", "x", "x", "x", "x")
        assert grimoire_setup.check_config_file(tmp_path / "nope.yaml", cfg, "core") == []


# ── Tests: check_copilot_instructions ─────────────────────────────────────────


class TestCheckCopilotInstructions:
    def test_detects_all_diffs(self, project_tree: Path):
        cfg = UserConfig("my-project", "Alice", "English", "English", "intermediate")
        path = project_tree / ".github" / "copilot-instructions.md"
        diffs = grimoire_setup.check_copilot_instructions(path, cfg)
        keys = {d.key for d in diffs}
        assert "Project" in keys
        assert "User" in keys
        assert "Communication Language" in keys
        assert "User Skill Level" in keys

    def test_no_diffs_when_synced(self, synced_tree: Path):
        cfg = UserConfig("synced", "Bob", "Français", "Français", "expert")
        path = synced_tree / ".github" / "copilot-instructions.md"
        assert grimoire_setup.check_copilot_instructions(path, cfg) == []


# ── Tests: apply_config_file ──────────────────────────────────────────────────


class TestApplyConfigFile:
    def test_updates_bmm(self, project_tree: Path):
        cfg = UserConfig("new-proj", "NewUser", "English", "English", "beginner")
        path = project_tree / "_bmad" / "bmm" / "config.yaml"
        assert grimoire_setup.apply_config_file(path, cfg, "bmm") is True
        text = path.read_text(encoding="utf-8")
        assert "user_name: NewUser" in text
        assert "communication_language: English" in text
        assert "project_name: new-proj" in text
        assert "user_skill_level: beginner" in text

    def test_updates_core(self, project_tree: Path):
        cfg = UserConfig("x", "NewUser", "English", "English", "x")
        path = project_tree / "_bmad" / "core" / "config.yaml"
        assert grimoire_setup.apply_config_file(path, cfg, "core") is True
        text = path.read_text(encoding="utf-8")
        assert "user_name: NewUser" in text
        assert "communication_language: English" in text

    def test_preserves_non_user_fields(self, project_tree: Path):
        cfg = UserConfig("x", "NewUser", "English", "English", "x")
        path = project_tree / "_bmad" / "bmm" / "config.yaml"
        grimoire_setup.apply_config_file(path, cfg, "bmm")
        text = path.read_text(encoding="utf-8")
        assert "planning_artifacts:" in text
        assert "implementation_artifacts:" in text
        assert "project_knowledge:" in text

    def test_no_change_returns_false(self, project_tree: Path):
        cfg = UserConfig("old-project", "OldUser", "Français", "Français", "expert")
        path = project_tree / "_bmad" / "bmm" / "config.yaml"
        assert grimoire_setup.apply_config_file(path, cfg, "bmm") is False

    def test_missing_file_returns_false(self, tmp_path: Path):
        cfg = UserConfig("x", "x", "x", "x", "x")
        assert grimoire_setup.apply_config_file(tmp_path / "nope.yaml", cfg, "core") is False


# ── Tests: apply_copilot_instructions ─────────────────────────────────────────


class TestApplyCopilotInstructions:
    def test_updates_all_fields(self, project_tree: Path):
        cfg = UserConfig("new-proj", "NewUser", "English", "English", "beginner")
        path = project_tree / ".github" / "copilot-instructions.md"
        assert grimoire_setup.apply_copilot_instructions(path, cfg) is True
        text = path.read_text(encoding="utf-8")
        assert "**Project**: new-proj" in text
        assert "**User**: NewUser" in text
        assert "**Communication Language**: English" in text
        assert "**Document Output Language**: English" in text
        assert "**User Skill Level**: beginner" in text

    def test_no_change_returns_false(self, project_tree: Path):
        cfg = UserConfig("old-project", "OldUser", "Français", "Français", "expert")
        path = project_tree / ".github" / "copilot-instructions.md"
        assert grimoire_setup.apply_copilot_instructions(path, cfg) is False


# ── Tests: apply_project_context ──────────────────────────────────────────────


class TestApplyProjectContext:
    def test_updates_all_user_fields(self, project_tree: Path):
        cfg = UserConfig("new-proj", "NewUser", "English", "English", "beginner")
        path = project_tree / "project-context.yaml"
        assert grimoire_setup.apply_project_context(path, cfg) is True
        text = path.read_text(encoding="utf-8")
        assert 'name: "new-proj"' in text
        assert 'name: "NewUser"' in text
        assert 'language: "English"' in text
        assert 'document_language: "English"' in text
        assert 'skill_level: "beginner"' in text

    def test_preserves_other_sections(self, project_tree: Path):
        cfg = UserConfig("new-proj", "NewUser", "EN", "EN", "expert")
        path = project_tree / "project-context.yaml"
        grimoire_setup.apply_project_context(path, cfg)
        text = path.read_text(encoding="utf-8")
        assert "stack:" in text
        assert "memory:" in text
        assert "backend:" in text

    def test_no_change_returns_false(self, project_tree: Path):
        cfg = UserConfig("my-project", "Alice", "English", "English", "intermediate")
        path = project_tree / "project-context.yaml"
        assert grimoire_setup.apply_project_context(path, cfg) is False

    def test_distinguishes_project_name_from_user_name(self, project_tree: Path):
        cfg = UserConfig("ProjectX", "UserY", "FR", "FR", "expert")
        path = project_tree / "project-context.yaml"
        grimoire_setup.apply_project_context(path, cfg)
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        # Find the project.name and user.name lines
        proj_name_line = None
        user_name_line = None
        section = ""
        for line in lines:
            s = line.strip()
            if s and not s.startswith("#") and not line[0:1].isspace() and ":" in s:
                section = s.split(":")[0].strip()
            if section == "project" and s.startswith("name:"):
                proj_name_line = s
            elif section == "user" and s.startswith("name:"):
                user_name_line = s
        assert proj_name_line == 'name: "ProjectX"'
        assert user_name_line == 'name: "UserY"'


# ── Tests: run_check ──────────────────────────────────────────────────────────


class TestRunCheck:
    def test_finds_all_diffs(self, project_tree: Path):
        cfg = UserConfig("my-project", "Alice", "English", "English", "intermediate")
        report = grimoire_setup.run_check(project_tree, cfg)
        assert not report.is_synced
        files_with_diffs = {d.file for d in report.diffs}
        # Should find diffs in all module configs + copilot-instructions
        assert any("bmm" in f for f in files_with_diffs)
        assert any("core" in f for f in files_with_diffs)
        assert any("copilot-instructions" in f for f in files_with_diffs)

    def test_all_synced(self, synced_tree: Path):
        cfg = UserConfig("synced", "Bob", "Français", "Français", "expert")
        report = grimoire_setup.run_check(synced_tree, cfg)
        assert report.is_synced


# ── Tests: run_apply ──────────────────────────────────────────────────────────


class TestRunApply:
    def test_syncs_all_files(self, project_tree: Path):
        cfg = UserConfig("my-project", "Alice", "English", "English", "intermediate")
        report = grimoire_setup.run_apply(project_tree, cfg)
        assert report.is_synced
        assert len(report.updated_files) > 0

    def test_updated_files_list(self, project_tree: Path):
        cfg = UserConfig("new-proj", "NewUser", "English", "English", "beginner")
        report = grimoire_setup.run_apply(project_tree, cfg)
        assert "project-context.yaml" in report.updated_files
        assert "_bmad/bmm/config.yaml" in report.updated_files
        assert "_bmad/core/config.yaml" in report.updated_files
        assert ".github/copilot-instructions.md" in report.updated_files

    def test_missing_module_skipped(self, tmp_path: Path):
        (tmp_path / "project-context.yaml").write_text(
            "project:\n  name: x\nuser:\n  name: y\n", encoding="utf-8"
        )
        cfg = UserConfig("x", "y", "FR", "FR", "expert")
        report = grimoire_setup.run_apply(tmp_path, cfg)
        assert len(report.skipped_files) > 0

    def test_idempotent(self, project_tree: Path):
        cfg = UserConfig("my-project", "Alice", "English", "English", "intermediate")
        grimoire_setup.run_apply(project_tree, cfg)
        report2 = grimoire_setup.run_apply(project_tree, cfg)
        assert report2.is_synced
        assert len(report2.updated_files) == 0


# ── Tests: CLI main() ────────────────────────────────────────────────────────


class TestMainCLI:
    def test_check_returns_1_on_desync(self, project_tree: Path):
        rc = grimoire_setup.main(["--project-root", str(project_tree), "--check"])
        assert rc == 1

    def test_check_returns_0_on_sync(self, synced_tree: Path):
        rc = grimoire_setup.main(["--project-root", str(synced_tree), "--check"])
        assert rc == 0

    def test_check_json_output(self, project_tree: Path, capsys):
        grimoire_setup.main(["--project-root", str(project_tree), "--check", "--json"])
        out = capsys.readouterr().out
        data = json.loads(out)
        assert data["synced"] is False
        assert len(data["diffs"]) > 0

    def test_sync_mode(self, project_tree: Path):
        rc = grimoire_setup.main(["--project-root", str(project_tree), "--sync"])
        assert rc == 0
        # Verify sync happened
        rc2 = grimoire_setup.main(["--project-root", str(project_tree), "--check"])
        assert rc2 == 0

    def test_cli_overrides(self, project_tree: Path):
        rc = grimoire_setup.main([
            "--project-root", str(project_tree),
            "--user", "NewUser",
            "--lang", "Deutsch",
        ])
        assert rc == 0
        cfg = grimoire_setup.load_project_context(project_tree / "project-context.yaml")
        assert cfg.user_name == "NewUser"
        assert cfg.communication_language == "Deutsch"
        # Unchanged fields kept from original
        assert cfg.project_name == "my-project"

    def test_missing_project_context(self, tmp_path: Path):
        rc = grimoire_setup.main(["--project-root", str(tmp_path), "--check"])
        assert rc == 1

    def test_missing_project_context_json(self, tmp_path: Path, capsys):
        rc = grimoire_setup.main(["--project-root", str(tmp_path), "--check", "--json"])
        assert rc == 1
        out = capsys.readouterr().out
        data = json.loads(out)
        assert "error" in data

    def test_sync_json_output(self, project_tree: Path, capsys):
        grimoire_setup.main(["--project-root", str(project_tree), "--sync", "--json"])
        out = capsys.readouterr().out
        data = json.loads(out)
        assert data["synced"] is True
        assert len(data["updated"]) > 0

    def test_sync_idempotent(self, project_tree: Path):
        grimoire_setup.main(["--project-root", str(project_tree), "--sync"])
        rc = grimoire_setup.main(["--project-root", str(project_tree), "--check"])
        assert rc == 0


# ── Tests: SetupReport dataclass ─────────────────────────────────────────────


class TestSetupReport:
    def test_is_synced_empty(self):
        r = SetupReport()
        assert r.is_synced is True

    def test_is_synced_with_diffs(self):
        r = SetupReport(diffs=[ConfigDiff("f", "k", "a", "b")])
        assert r.is_synced is False
