"""Registre des checks du standard agentique.

Chaque identifiant émis par un vérificateur est déclaré ici avec la dimension de
score qui le porte. Avant ce registre, le routage se faisait par correspondance de
préfixe (``DIMENSION_CHECK_PREFIXES``) : un préfixe non déclaré tombait
silencieusement dans le bucket ``artifacts``, et quinze checks s'y trouvaient — dont
les quatre ``gates.*``, que le préfixe ``gate.`` ne pouvait pas atteindre.

Une déclaration explicite rend cette faute impossible : ``test_every_emitted_check_is_registered``
échoue sur tout identifiant absent du registre.
"""

from __future__ import annotations

CHECK_DIMENSIONS: dict[str, str] = {
    # -- artifacts -----------------------------------------------------
    "actions.invalid": "artifacts",
    "compliance.owner_missing": "artifacts",
    "compliance.unknown_status": "artifacts",
    "manifest.profile_mismatch": "artifacts",
    "manifest.project_missing": "artifacts",
    "manifest.required_artifacts_mismatch": "artifacts",
    "manifest.task_id_mismatch": "artifacts",
    "mission.profile_missing": "artifacts",
    "mission.project_missing": "artifacts",
    "mission.upstream_missing": "artifacts",
    "risks.invalid": "artifacts",
    "profile.dry_run_missing": "artifacts",
    "profile.environment_missing": "artifacts",
    "profile.rollback_missing": "artifacts",
    "profile.slo_missing": "artifacts",
    "profile.telemetry_missing": "artifacts",
    "profile.workspace_missing": "artifacts",
    "score.dimensions_missing": "artifacts",
    "score.thresholds_missing": "artifacts",
    "waivers.invalid": "artifacts",
    # -- ci_release_gate -----------------------------------------------
    "cluster.actions_missing": "ci_release_gate",
    "cluster.dry_run_required": "ci_release_gate",
    "cluster.rollback_required": "ci_release_gate",
    "env.environments_missing": "ci_release_gate",
    "env.production_unguarded": "ci_release_gate",
    "merge.classes_incomplete": "ci_release_gate",
    "merge.hard_not_escalated": "ci_release_gate",
    "merge.no_retry_budget": "ci_release_gate",
    # -- context_contract ----------------------------------------------
    "compression.atomicity_dropped": "context_contract",
    "compression.constraints_dropped": "context_contract",
    "compression.evidence_dropped": "context_contract",
    "compression.provenance_dropped": "context_contract",
    "compression.ratio_invalid": "context_contract",
    "context.budget_invalid": "context_contract",
    "context.budget_missing": "context_contract",
    "context.bundle_sections_invalid": "context_contract",
    "context.bundle_sections_missing": "context_contract",
    "context.checks_invalid": "context_contract",
    "context.checks_missing": "context_contract",
    "context.inputs_invalid": "context_contract",
    "context.inputs_missing": "context_contract",
    "context.redaction_missing": "context_contract",
    "context.redaction_required": "context_contract",
    # -- decision_graph ------------------------------------------------
    "council.no_budget_cap": "decision_graph",
    "council.no_triggers": "decision_graph",
    "council.no_veto": "decision_graph",
    "council.quorum_too_low": "decision_graph",
    "decision.id_missing": "decision_graph",
    "decision.inputs_missing": "decision_graph",
    "decision.outputs_missing": "decision_graph",
    "decision.record_schema_missing": "decision_graph",
    "decision.required_types_missing": "decision_graph",
    "decision.type_invalid": "decision_graph",
    "decision.types_missing": "decision_graph",
    # -- evidence_gates ------------------------------------------------
    "browser.dom_required": "evidence_gates",
    "browser.domains_invalid": "evidence_gates",
    "browser.screenshot_required": "evidence_gates",
    "evidence.inventory_placeholder": "evidence_gates",
    "evidence.pending_gate": "evidence_gates",
    "evidence.summary_placeholder": "evidence_gates",
    "gate.compliance_score_missing": "evidence_gates",
    "gate.decision_trace_missing": "evidence_gates",
    "gate.evidence_pack_missing": "evidence_gates",
    # Émis par l'évaluateur de gates, pas par le vérificateur de board : la tâche
    # absente empêche d'évaluer les gates, elle ne décrit pas un board mal formé.
    # Aucun `board.*` ne couvre ce cas, donc pas de double compte.
    "gate.task_not_on_board": "evidence_gates",
    "gates.required_evidence_missing": "evidence_gates",
    "gates.transition.from_missing": "evidence_gates",
    "gates.transition.id_missing": "evidence_gates",
    "gates.transition.required_evidence_missing": "evidence_gates",
    "gates.transition.to_missing": "evidence_gates",
    "gates.transition_invalid": "evidence_gates",
    "gates.transitions_missing": "evidence_gates",
    "gates.unknown_state": "evidence_gates",
    "visual.journey_not_required": "evidence_gates",
    "visual.missing_artifact_kinds": "evidence_gates",
    "visual.no_triggers": "evidence_gates",
    # -- hook_registry -------------------------------------------------
    "firewall.isolation_disabled": "hook_registry",
    "firewall.no_sources": "hook_registry",
    "firewall.override_allowed": "hook_registry",
    "firewall.source_not_quarantined": "hook_registry",
    "hooks.action_missing": "hook_registry",
    "hooks.id_missing": "hook_registry",
    "hooks.invalid": "hook_registry",
    "hooks.none": "hook_registry",
    "hooks.phase_missing": "hook_registry",
    "hooks.reason_missing": "hook_registry",
    "hooks.rule_ref_missing": "hook_registry",
    "hooks.unknown_action": "hook_registry",
    "hooks.unknown_phase": "hook_registry",
    "privilege.boundary_invalid": "hook_registry",
    "privilege.boundary_undeclared": "hook_registry",
    "privilege.infra_token_exposed": "hook_registry",
    "privilege.scrub_disabled": "hook_registry",
    "remote.age_unbounded": "hook_registry",
    "remote.branches_unbounded": "hook_registry",
    "remote.reachability_unchecked": "hook_registry",
    "remote.stale_check_disabled": "hook_registry",
    "tools.blast_radius_allowlist_empty": "hook_registry",
    "tools.blast_radius_defaults_missing": "hook_registry",
    "tools.blast_radius_id_missing": "hook_registry",
    "tools.blast_radius_invalid": "hook_registry",
    "tools.blast_radius_network_invalid": "hook_registry",
    "tools.blast_radius_production_allow": "hook_registry",
    "tools.blast_radius_production_invalid": "hook_registry",
    "tools.blast_radius_undeclared": "hook_registry",
    "tools.blast_radius_unenforced": "hook_registry",
    "tools.blast_radius_writable_invalid": "hook_registry",
    "tools.blast_radius_writable_outside_root": "hook_registry",
    "workspace.isolation_undeclared": "hook_registry",
    "workspace.network_open": "hook_registry",
    "workspace.writable_unbounded": "hook_registry",
    # -- knowledge_registry --------------------------------------------
    "docgraph.provenance_optional": "knowledge_registry",
    "docgraph.relations_disabled": "knowledge_registry",
    "docgraph.sources_missing": "knowledge_registry",
    "knowledge.explicit_source_of_truth_required": "knowledge_registry",
    "knowledge.index_manifest_missing": "knowledge_registry",
    "knowledge.index_manifest_outside_root": "knowledge_registry",
    "knowledge.invalid_source": "knowledge_registry",
    "knowledge.knowledge_is_not_memory": "knowledge_registry",
    "knowledge.knowledge_is_not_session_context": "knowledge_registry",
    "knowledge.locator_missing": "knowledge_registry",
    "knowledge.locator_not_found": "knowledge_registry",
    "knowledge.locator_outside_root": "knowledge_registry",
    "knowledge.no_real_source": "knowledge_registry",
    "knowledge.rules_missing": "knowledge_registry",
    "knowledge.sources_missing": "knowledge_registry",
    "knowledge.trust_level_missing": "knowledge_registry",
    "knowledge.trust_missing": "knowledge_registry",
    "knowledge.truth_low_trust": "knowledge_registry",
    "knowledge_index.missing": "knowledge_registry",
    "knowledge_index.normative_artifacts_invalid": "knowledge_registry",
    "knowledge_index.patterns_invalid": "knowledge_registry",
    "knowledge_index.sources_invalid": "knowledge_registry",
    # -- memory_os -----------------------------------------------------
    "memory.os_contract_missing": "memory_os",
    "memory.os_graph_projection_target": "memory_os",
    "memory.os_hot_memory_target": "memory_os",
    "memory.os_legacy_sources_missing": "memory_os",
    "memory.os_promotion_gates_missing": "memory_os",
    "memory.os_runtime_commands_missing": "memory_os",
    "memory.os_semantic_memory_target": "memory_os",
    "memory.os_sidecar_target": "memory_os",
    "memory.os_target_missing": "memory_os",
    # -- memory_policy -------------------------------------------------
    "integrity.drift_unchecked": "memory_policy",
    "integrity.no_expiry": "memory_policy",
    "integrity.poisoning_unchecked": "memory_policy",
    "integrity.provenance_unchecked": "memory_policy",
    "memory.allowed_context_uses_missing": "memory_policy",
    "memory.context_uses_invalid": "memory_policy",
    "memory.freshness_missing": "memory_policy",
    "memory.memory_id_missing": "memory_policy",
    "memory.provider_compatibility_invalid": "memory_policy",
    "memory.provider_compatibility_missing": "memory_policy",
    "memory.read_policy_missing": "memory_policy",
    "memory.redaction_policy_missing": "memory_policy",
    "memory.required_types_missing": "memory_policy",
    "memory.retention_missing": "memory_policy",
    "memory.scope_missing": "memory_policy",
    "memory.trust_level_missing": "memory_policy",
    "memory.type_invalid": "memory_policy",
    "memory.type_missing": "memory_policy",
    "memory.types_missing": "memory_policy",
    "memory.write_policy_missing": "memory_policy",
    # -- orchestration_policy ------------------------------------------
    "flowdsl.export_undeclared": "orchestration_policy",
    "flowdsl.steps_missing": "orchestration_policy",
    "k8s.crd_missing": "orchestration_policy",
    "k8s.resource_limits_missing": "orchestration_policy",
    "k8s.service_account_missing": "orchestration_policy",
    "k8s.telemetry_missing": "orchestration_policy",
    "orchestration.role.allowed_memory_types_missing": "orchestration_policy",
    "orchestration.role.allowed_providers_missing": "orchestration_policy",
    "orchestration.role.allowed_tools_missing": "orchestration_policy",
    "orchestration.role.autonomy_level_missing": "orchestration_policy",
    "orchestration.role.escalation_triggers_missing": "orchestration_policy",
    "orchestration.role.handoff_contracts_missing": "orchestration_policy",
    "orchestration.role.persona_or_archetype_missing": "orchestration_policy",
    "orchestration.role.responsibilities_missing": "orchestration_policy",
    "orchestration.role.review_gates_missing": "orchestration_policy",
    "orchestration.role.role_id_missing": "orchestration_policy",
    "orchestration.role.rollback_policy_missing": "orchestration_policy",
    "orchestration.role_invalid": "orchestration_policy",
    "orchestration.roles_missing": "orchestration_policy",
    "runtime.lifecycle_incomplete": "orchestration_policy",
    "runtime.logs_undeclared": "orchestration_policy",
    "runtime.resources_unbounded": "orchestration_policy",
    "wsm.initial_undeclared": "orchestration_policy",
    "wsm.states_missing": "orchestration_policy",
    "wsm.transition_invalid": "orchestration_policy",
    "wsm.transitions_missing": "orchestration_policy",
    # -- provider_policy -----------------------------------------------
    "cost.no_budget": "provider_policy",
    "cost.no_pricing": "provider_policy",
    "cost.no_slo": "provider_policy",
    "cost.pricing_incomplete": "provider_policy",
    "providers.capabilities_missing": "provider_policy",
    "providers.data_policy_missing": "provider_policy",
    "providers.default_not_enabled": "provider_policy",
    "providers.default_unknown": "provider_policy",
    "providers.enabled_not_bool": "provider_policy",
    "providers.hosted_forbidden_missing": "provider_policy",
    "providers.id_missing": "provider_policy",
    "providers.invalid_entry": "provider_policy",
    "providers.models_missing": "provider_policy",
    "providers.none": "provider_policy",
    "providers.none_enabled": "provider_policy",
    "providers.routing_missing": "provider_policy",
    "providers.routing_policy_weak": "provider_policy",
    "providers.routing_unknown_fallback": "provider_policy",
    "providers.unknown_fallback": "provider_policy",
    # -- rule_packs ----------------------------------------------------
    "guardrail.faces_missing": "rule_packs",
    "guardrail.input_missing": "rule_packs",
    "guardrail.invalid_mode": "rule_packs",
    "guardrail.model_missing": "rule_packs",
    "guardrail.no_violation_action": "rule_packs",
    "guardrail.output_missing": "rule_packs",
    "guardrail.tool_missing": "rule_packs",
    "guardrail.unversioned": "rule_packs",
    "patterns.categories_missing": "rule_packs",
    "patterns.category_missing": "rule_packs",
    "patterns.check_refs_missing": "rule_packs",
    "patterns.id_missing": "rule_packs",
    "patterns.intent_missing": "rule_packs",
    "patterns.invalid": "rule_packs",
    "patterns.maturity_missing": "rule_packs",
    "patterns.none": "rule_packs",
    "patterns.required_artifacts_invalid": "rule_packs",
    "patterns.required_artifacts_missing": "rule_packs",
    "patterns.source_normative_missing": "rule_packs",
    "patterns.unknown_category": "rule_packs",
    "rules.action_missing": "rule_packs",
    "rules.condition_missing": "rule_packs",
    "rules.event_missing": "rule_packs",
    "rules.family_missing": "rule_packs",
    "rules.id_missing": "rule_packs",
    "rules.invalid": "rule_packs",
    "rules.none": "rule_packs",
    "rules.phase_missing": "rule_packs",
    "rules.remediation_missing": "rule_packs",
    "rules.severity_missing": "rule_packs",
    "rules.source_normative_missing": "rule_packs",
    "rules.unknown_action": "rule_packs",
    "rules.unknown_phase": "rule_packs",
    # -- runtime_journal -----------------------------------------------
    "promptver.evals_unlinked": "runtime_journal",
    "promptver.tracking_incomplete": "runtime_journal",
    # -- task_board ----------------------------------------------------
    "board.blocker_reason_missing": "task_board",
    "board.context_bundle_ref_outside_root": "task_board",
    "board.decision_trace_missing": "task_board",
    "board.decision_trace_ref_outside_root": "task_board",
    "board.evidence_pack_ref_outside_root": "task_board",
    "board.no_tasks": "task_board",
    "board.remediation_ref_outside_root": "task_board",
    "board.states_incomplete": "task_board",
    "board.status_invalid": "task_board",
    "board.task.acceptance_criteria_missing": "task_board",
    "board.task.evidence_pack_ref_missing": "task_board",
    "board.task.status_missing": "task_board",
    "board.task.task_id_missing": "task_board",
    "board.task.title_missing": "task_board",
    "board.task_id_invalid": "task_board",
    "board.task_invalid": "task_board",
    "board.tasks_missing": "task_board",
    "task.context_placeholder": "task_board",
    "task.pending_gate": "task_board",
    "task.state_placeholder": "task_board",
    "task.tool_boundary_placeholder": "task_board",
}


DEFAULT_SCORE_DIMENSIONS = {
    "artifacts": 10,
    "provider_policy": 10,
    "knowledge_registry": 10,
    "task_board": 10,
    "memory_policy": 10,
    "memory_os": 10,
    "context_contract": 10,
    "decision_graph": 6,
    "rule_packs": 6,
    "hook_registry": 6,
    "orchestration_policy": 10,
    "evidence_gates": 10,
    "runtime_journal": 4,
    "ci_release_gate": 6,
}
"""Poids par dimension de score. La somme fait le total sur lequel le score est calculé."""


DIMENSION_CHECK_PREFIXES = {
    "artifacts": ("artifact.", "yaml.", "manifest.", "mission."),
    "provider_policy": ("providers.", "cost."),
    "knowledge_registry": ("knowledge.", "knowledge_index.", "docgraph."),
    "task_board": ("board.", "task."),
    "memory_os": ("memory.os_",),
    "memory_policy": ("memory.", "integrity."),
    "context_contract": ("context.", "compression."),
    "decision_graph": ("decision.", "council."),
    "rule_packs": ("rules.", "guardrail."),
    "hook_registry": ("hooks.", "tools.blast_radius", "privilege.", "firewall.", "workspace."),
    "runtime_journal": ("journal.", "promptver."),
    "orchestration_policy": ("orchestration.", "wsm.", "flowdsl.", "runtime.", "k8s."),
    "evidence_gates": ("evidence.", "gate.", "visual.", "browser."),
    "ci_release_gate": ("release.", "merge.", "cluster.", "env."),
}
"""Repli par préfixe, conservé pour les checks qu'un projet émet lui-même.

``CHECK_DIMENSIONS`` reste la source de vérité pour tout check émis par le kit.
"""


def dimension_for(check_id: str) -> str | None:
    """Return the score dimension carrying ``check_id``, or ``None`` if unregistered.

    ``None`` is deliberate: an unregistered check must be visible as such rather
    than absorbed by a default bucket.
    """
    return CHECK_DIMENSIONS.get(check_id)
