"""Catalog of every file the kit has ever shipped, keyed by content digest.

``grimoire migrate`` has one hard question to answer for each file in a
pre-boundary project: did the *user* write this, or did some past version of
the kit? Answering it wrong in one direction destroys a customisation; wrong in
the other freezes a stale file in ``overrides/`` where no update will ever
reach it again.

The catalog answers it by content: a digest the kit has shipped at some point
is kit-owned and safe to regenerate. Anything else belongs to the project.
Keying by digest instead of by path is what lets a file that moved between
layouts across versions still be recognised.

Generated by ``scripts/gen-kit-hashes.py``; absent catalog means "recognise
nothing", which degrades migration to the safe side — everything is treated as
the project's own.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
from functools import lru_cache
from importlib.resources import files
from pathlib import Path
from typing import Any

_CATALOG_NAME = "kit-file-hashes.json"


def _candidate_paths() -> list[Path]:
    """Where the catalog may live, wheel install first, then a dev checkout."""
    candidates: list[Path] = []
    with contextlib.suppress(ModuleNotFoundError, TypeError):  # wheel layout
        candidates.append(Path(str(files("grimoire"))) / "data" / _CATALOG_NAME)
    here = Path(__file__).resolve()
    # src/grimoire/core/kit_hashes.py → repo root
    candidates.append(here.parent.parent.parent.parent / "registry" / _CATALOG_NAME)
    return candidates


@lru_cache(maxsize=1)
def load_catalog() -> dict[str, dict[str, Any]]:
    """``digest -> {"version", "path"}`` for every file the kit has shipped."""
    for path in _candidate_paths():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        digests = data.get("digests")
        if isinstance(digests, dict):
            return digests
    return {}


def digest_of(path: Path) -> str:
    """SHA-256 of *path*, or ``""`` when it cannot be read."""
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError:
        return ""


def shipped_by_kit(path: Path) -> dict[str, Any] | None:
    """Catalog entry when *path* holds content the kit shipped, else ``None``."""
    digest = digest_of(path)
    if not digest:
        return None
    return load_catalog().get(digest)
