"""Project scaffolding engine — creates a complete Grimoire project structure.

The engine works in two phases:

1. **Plan** — build a ``ScaffoldPlan`` describing every directory, file copy,
   and template rendering without touching the filesystem.
2. **Execute** — apply the plan atomically (as much as possible).

This separation makes ``--dry-run`` trivial and unit testing straightforward.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from string import Template

from grimoire.archetypes import bundled_path as archetypes_path
from grimoire.core.archetype_resolver import ResolvedArchetype
from grimoire.core.scanner import ScanResult
from grimoire.data import framework_path

# ── Data models ───────────────────────────────────────────────────────────────


@dataclass
class FileCopy:
    """A file to copy from *src* to *dst*."""

    src: Path
    dst: Path
    label: str = ""


@dataclass
class TemplateRender:
    """A template file to render with *variables* and write to *dst*."""

    dst: Path
    content: str
    label: str = ""


@dataclass
class ScaffoldPlan:
    """Everything the scaffolder intends to do — inspectable before execution."""

    directories: list[Path] = field(default_factory=list)
    copies: list[FileCopy] = field(default_factory=list)
    templates: list[TemplateRender] = field(default_factory=list)

    @property
    def total_operations(self) -> int:
        return len(self.directories) + len(self.copies) + len(self.templates)


@dataclass
class ScaffoldResult:
    """Outcome of executing a plan."""

    created_dirs: list[str] = field(default_factory=list)
    copied_files: list[str] = field(default_factory=list)
    rendered_files: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def total(self) -> int:
        return len(self.created_dirs) + len(self.copied_files) + len(self.rendered_files)


# ── Templates ─────────────────────────────────────────────────────────────────

_PROJECT_CONTEXT_TPL = """\
# Grimoire Kit — Project Context
# Auto-generated by: grimoire init
# Run: grimoire doctor  to validate this file.

project:
  name: "$project_name"
  description: ""
  type: "$project_type"
  stack: [$stack_list]
  repos:
    - name: "$project_name"
      path: "."
      default_branch: "main"

user:
  name: "$user_name"
  language: "$language"
  skill_level: "$skill_level"

memory:
  backend: "$backend"

agents:
  archetype: "$archetype"
  custom_agents: []

installed_archetypes: [$archetype_list]
"""

_MEMORY_CONFIG_TPL = """\
# Grimoire Memory Configuration — auto-generated
user_name: "$user_name"
communication_language: "$language"
document_output_language: "$language"
"""

_SHARED_CONTEXT_DEFAULT = """\
# Shared Context — Project Awareness
# This file is loaded by agents to understand your project.

## Project
- **Name**: $project_name
- **Type**: $project_type
- **Stack**: $stack_list

## Conventions
- Communication language: $language

## Key Decisions
(none yet — decisions will be logged here as the project evolves)
"""

_DECISIONS_LOG = """\
# Journal de Décisions — $project_name

> Les agents enregistrent ici les décisions architecturales et techniques significatives.
> Tu peux aussi en ajouter manuellement.

## Format

```
### [YYYY-MM-DD] Titre court de la décision
- **Contexte** : Pourquoi cette décision s'est posée
- **Décision** : Ce qui a été choisi
- **Alternatives rejetées** : Ce qui a été écarté et pourquoi
- **Agent** : Qui a pris/suggéré cette décision
```

## Décisions

*(Les décisions seront loguées ici au fil du projet)*
"""

_MANIFEST_HEADER = "name,file,role,icon\n"  # kept for backward compat

_COPILOT_INSTRUCTIONS_TPL = """\
# Copilot Instructions — $project_name

> Auto-generated by Grimoire Kit
> Archetype: $archetype | Memory: $backend

## Quick Start

1. Ouvre **Copilot Chat** dans VS Code
2. Tape **@concierge** pour parler à Marcel, ton concierge IA
3. Décris-lui ton projet — il mettra à jour le contexte pour toute l'équipe d'agents
4. Pose ta première question ou demande

> Marcel connaît tous les agents et t'aiguille vers le bon spécialiste.
> Tu n'as pas besoin de savoir quel agent utiliser — il s'en occupe.

## Project Context

- **Name**: $project_name
- **User**: $user_name
- **Language**: $language

## Installed Agents

$agents_table

> **Accès** : Seul `@concierge` est accessible directement dans Copilot Chat.
> Les autres agents sont routés automatiquement par Marcel selon ta demande.

Agent files are in `.github/agents/` — VS Code discovers them automatically.

## File Ownership

| Zone | Propriétaire | Règle |
|------|-------------|-------|
| `project-context.yaml` | Toi | Configuration globale du projet |
| `_grimoire/_memory/shared-context.md` | Toi + Agents | **Remplis en priorité** — briefing lu par TOUS les agents |
| `_grimoire/_memory/decisions-log.md` | Agents | Log auto des décisions architecturales |
| `_grimoire/_memory/failure-museum.md` | Agents | Catalogue auto des erreurs et résolutions |
| `_grimoire/_config/custom/agents/` | Framework | Agents internes — personnaliser avec prudence |
| `.github/agents/` | Auto-généré | Wrappers VS Code — ne pas modifier manuellement |
| `_grimoire-output/` | Agents | Outputs de travail — lecture seule pour l'humain |

## Archetype DNA

Le fichier `_grimoire/_config/archetype.dna.yaml` définit les **traits**,
**contraintes** et **valeurs** du projet selon l'archétype choisi ($archetype).
Les agents le consultent pour adapter leur comportement.

## Grimoire Structure

```
_grimoire/
  _config/
    archetype.dna.yaml     # Traits, contraintes, valeurs (NE PAS SUPPRIMER)
    custom/
      agents/              # Agents IA du projet (personnalisables)
      prompt-templates/    # Templates de prompts
      workflows/           # Workflows custom
      agent-base.md        # Protocole de base (NE PAS MODIFIER)
      cc-verify.sh         # Vérificateur de Completion Contract
    agent-manifest.csv     # Registre des agents installés
  _memory/
    shared-context.md      # Contexte partagé — REMPLIR EN PREMIER
    config.yaml            # Config mémoire
    decisions-log.md       # Journal de décisions (auto)
    failure-museum.md      # Musée des erreurs (auto)
    session-state.md       # État de session (auto)
_grimoire-output/
  .runs/                   # Sessions de travail (exclu du git)
project-context.yaml       # Config globale du projet
.gitignore                 # Patterns Grimoire auto-ajoutés
```

## Conventions

1. **Language**: Always respond in $language
2. **Completion Contract**: Avant chaque commit, vérifier avec `bash _grimoire/_config/custom/cc-verify.sh`
3. **Context**: Charger `_grimoire/_memory/shared-context.md` au démarrage
4. **Decisions**: Les décisions sont loguées dans `_grimoire/_memory/decisions-log.md`
5. **Errors**: Les erreurs significatives sont documentées dans `_grimoire/_memory/failure-museum.md`
6. **No hallucination**: Quand une information n'est pas dans shared-context.md, demander à l'utilisateur plutôt que deviner

## CLI Reference

| Commande | Usage |
|----------|-------|
| `grimoire init` | Initialiser un nouveau projet Grimoire |
| `grimoire doctor` | Health check complet du projet |
| `grimoire status` | Voir les agents installés et leur état |
"""


# ── Scaffolder ────────────────────────────────────────────────────────────────


class ProjectScaffolder:
    """Build and execute a scaffold plan for a Grimoire project."""

    def __init__(
        self,
        target: Path,
        *,
        project_name: str,
        user_name: str,
        language: str,
        skill_level: str,
        scan: ScanResult | None,
        resolved: ResolvedArchetype,
        backend: str,
    ) -> None:
        self._target = target.resolve()
        self._project_name = project_name
        self._user_name = user_name
        self._language = language
        self._skill_level = skill_level
        self._scan = scan
        self._resolved = resolved
        self._backend = backend
        self._archetypes = archetypes_path()
        self._framework = framework_path()

    # ── Public API ────────────────────────────────────────────────────

    def plan(self) -> ScaffoldPlan:
        """Build a complete scaffold plan without touching the filesystem."""
        p = ScaffoldPlan()
        self._plan_directories(p)
        self._plan_meta_agents(p)
        self._plan_archetype_agents(p)
        self._plan_stack_agents(p)
        self._plan_feature_agents(p)
        self._plan_framework(p)
        self._plan_templates(p)
        self._plan_agent_wrappers(p)
        self._plan_copilot_instructions(p)
        self._plan_gitignore(p)
        return p

    def execute(self, plan: ScaffoldPlan) -> ScaffoldResult:
        """Execute a scaffold plan, writing to the filesystem."""
        result = ScaffoldResult()

        for d in plan.directories:
            d.mkdir(parents=True, exist_ok=True)
            result.created_dirs.append(str(d.relative_to(self._target)))

        for fc in plan.copies:
            fc.dst.parent.mkdir(parents=True, exist_ok=True)
            if fc.src.is_dir():
                shutil.copytree(fc.src, fc.dst, dirs_exist_ok=True)
            else:
                shutil.copy2(fc.src, fc.dst)
            result.copied_files.append(fc.label or str(fc.dst.relative_to(self._target)))

        for tr in plan.templates:
            tr.dst.parent.mkdir(parents=True, exist_ok=True)
            tr.dst.write_text(tr.content, encoding="utf-8")
            result.rendered_files.append(tr.label or str(tr.dst.relative_to(self._target)))

        return result

    # ── Planning helpers ──────────────────────────────────────────────

    def _agents_dir(self) -> Path:
        return self._target / "_grimoire" / "_config" / "custom" / "agents"

    def _memory_dir(self) -> Path:
        return self._target / "_grimoire" / "_memory"

    def _tpl_vars(self) -> dict[str, str]:
        stacks = [d.name for d in self._scan.stacks] if self._scan else []
        stack_list = ", ".join(f'"{s}"' for s in stacks) if stacks else ""
        archetypes = self._resolved.archetypes or (self._resolved.archetype,)
        archetype_list = ", ".join(f'"{a}"' for a in archetypes)
        return {
            "project_name": self._project_name,
            "user_name": self._user_name,
            "language": self._language,
            "skill_level": self._skill_level,
            "project_type": self._scan.project_type if self._scan else "generic",
            "stack_list": stack_list,
            "archetype": ", ".join(archetypes),
            "archetype_list": archetype_list,
            "backend": self._backend,
        }

    def _plan_directories(self, p: ScaffoldPlan) -> None:
        base = self._target
        dirs = [
            base / ".github" / "agents",
            base / "_grimoire" / "_config" / "custom" / "agents",
            base / "_grimoire" / "_config" / "custom" / "prompt-templates",
            base / "_grimoire" / "_config" / "custom" / "workflows",
            base / "_grimoire" / "_memory" / "agent-learnings",
            base / "_grimoire" / "_memory" / "session-summaries",
            base / "_grimoire" / "_memory" / "archives",
            base / "_grimoire-output" / ".runs" / "main",
            base / "_grimoire-output" / "team-vision",
            base / "_grimoire-output" / "team-build" / "stories",
            base / "_grimoire-output" / "team-build" / "test-reports",
            base / "_grimoire-output" / "team-ops",
            base / "_grimoire-output" / "contracts",
        ]
        p.directories.extend(dirs)

    def _plan_meta_agents(self, p: ScaffoldPlan) -> None:
        meta_dir = self._archetypes / "meta" / "agents"
        if not meta_dir.is_dir():
            return
        agents_dst = self._agents_dir()
        for md in sorted(meta_dir.glob("*.md")):
            p.copies.append(FileCopy(
                src=md,
                dst=agents_dst / md.name,
                label=f"meta/{md.stem}",
            ))

    def _plan_archetype_agents(self, p: ScaffoldPlan) -> None:
        archetypes = self._resolved.archetypes or (self._resolved.archetype,)
        for arch in archetypes:
            arch_dir = self._archetypes / arch
            if not arch_dir.is_dir():
                continue

            # Agents
            agents_src = arch_dir / "agents"
            if agents_src.is_dir():
                agents_dst = self._agents_dir()
                for md in sorted(agents_src.glob("*.md")):
                    # Skip if already planned (from a previous archetype layer)
                    if any(fc.dst == agents_dst / md.name for fc in p.copies):
                        continue
                    p.copies.append(FileCopy(
                        src=md,
                        dst=agents_dst / md.name,
                        label=f"{arch}/{md.stem}",
                    ))

            # Archetype DNA — merge multiple into composite
            dna_src = arch_dir / "archetype.dna.yaml"
            if dna_src.is_file():
                p.copies.append(FileCopy(
                    src=dna_src,
                    dst=self._target / "_grimoire" / "_config" / f"archetype.dna.{arch}.yaml",
                    label=f"{arch}/archetype.dna.yaml",
                ))
                # Also keep a primary DNA copy for backward compat (first archetype wins)
                primary_dst = self._target / "_grimoire" / "_config" / "archetype.dna.yaml"
                if not any(fc.dst == primary_dst for fc in p.copies):
                    p.copies.append(FileCopy(
                        src=dna_src,
                        dst=primary_dst,
                        label=f"{arch}/archetype.dna.yaml",
                    ))

            # Shared context template (first archetype with template wins)
            shared_tpl = arch_dir / "shared-context.tpl.md"
            shared_dst = self._memory_dir() / "shared-context.md"
            if shared_tpl.is_file() and not any(t.dst == shared_dst for t in p.templates):
                content = shared_tpl.read_text(encoding="utf-8")
                rendered = Template(content).safe_substitute(self._tpl_vars())
                p.templates.append(TemplateRender(
                    dst=shared_dst,
                    content=rendered,
                    label="shared-context.md (archetype)",
                ))

    def _plan_stack_agents(self, p: ScaffoldPlan) -> None:
        stack_agents_dir = self._archetypes / "stack" / "agents"
        if not stack_agents_dir.is_dir():
            return
        agents_dst = self._agents_dir()
        for agent_name in self._resolved.stack_agents:
            md = stack_agents_dir / f"{agent_name}.md"
            if md.is_file():
                p.copies.append(FileCopy(
                    src=md,
                    dst=agents_dst / md.name,
                    label=f"stack/{agent_name}",
                ))

    def _plan_feature_agents(self, p: ScaffoldPlan) -> None:
        agents_dst = self._agents_dir()
        for agent_name in self._resolved.feature_agents:
            # Known feature agent paths
            if agent_name == "vectus":
                src = self._archetypes / "features" / "vector-memory" / "vectus.md"
                if src.is_file():
                    p.copies.append(FileCopy(
                        src=src,
                        dst=agents_dst / "vectus.md",
                        label="feature/vectus",
                    ))

    def _plan_framework(self, p: ScaffoldPlan) -> None:
        fw = self._framework
        dst_custom = self._target / "_grimoire" / "_config" / "custom"

        # Core framework files
        for name in ("agent-base.md", "agent-base-compact.md"):
            src = fw / name
            if src.is_file():
                p.copies.append(FileCopy(src=src, dst=dst_custom / name, label=f"framework/{name}"))

        # Shell scripts
        for name in ("cc-verify.sh", "sil-collect.sh"):
            src = fw / name
            if src.is_file():
                p.copies.append(FileCopy(src=src, dst=dst_custom / name, label=f"framework/{name}"))

        # Prompt templates
        pt_src = fw / "prompt-templates"
        if pt_src.is_dir():
            p.copies.append(FileCopy(
                src=pt_src,
                dst=dst_custom / "prompt-templates",
                label="framework/prompt-templates/",
            ))

        # Workflows
        wf_src = fw / "workflows"
        if wf_src.is_dir():
            p.copies.append(FileCopy(
                src=wf_src,
                dst=dst_custom / "workflows",
                label="framework/workflows/",
            ))

        # Memory system
        mem_dst = self._memory_dir()
        for name in ("maintenance.py", "session-save.py"):
            src = fw / "memory" / name
            if src.is_file():
                p.copies.append(FileCopy(src=src, dst=mem_dst / name, label=f"memory/{name}"))

        backends_src = fw / "memory" / "backends"
        if backends_src.is_dir():
            p.copies.append(FileCopy(
                src=backends_src,
                dst=mem_dst / "backends",
                label="memory/backends/",
            ))

        # Memory templates
        for tpl_name in ("contradiction-log.tpl.md", "failure-museum.tpl.md"):
            src = fw / "memory" / tpl_name
            if src.is_file():
                dst_name = tpl_name.replace(".tpl", "")
                p.copies.append(FileCopy(src=src, dst=mem_dst / dst_name, label=f"memory/{dst_name}"))

    def _plan_templates(self, p: ScaffoldPlan) -> None:
        v = self._tpl_vars()

        # project-context.yaml
        p.templates.append(TemplateRender(
            dst=self._target / "project-context.yaml",
            content=Template(_PROJECT_CONTEXT_TPL).safe_substitute(v),
            label="project-context.yaml",
        ))

        # Memory config
        p.templates.append(TemplateRender(
            dst=self._memory_dir() / "config.yaml",
            content=Template(_MEMORY_CONFIG_TPL).safe_substitute(v),
            label="_grimoire/_memory/config.yaml",
        ))

        # Shared context (only if archetype didn't provide one)
        shared_dst = self._memory_dir() / "shared-context.md"
        if not any(t.dst == shared_dst for t in p.templates):
            p.templates.append(TemplateRender(
                dst=shared_dst,
                content=Template(_SHARED_CONTEXT_DEFAULT).safe_substitute(v),
                label="shared-context.md (default)",
            ))

        # Decisions log
        p.templates.append(TemplateRender(
            dst=self._memory_dir() / "decisions-log.md",
            content=_DECISIONS_LOG,
            label="decisions-log.md",
        ))

        # Session state
        p.templates.append(TemplateRender(
            dst=self._memory_dir() / "session-state.md",
            content="# Session State\n\nstatus: idle\nfirst_run: true\n",
            label="session-state.md",
        ))

        # Agent manifest (enriched with category + description)
        manifest_lines = ["name,file,category,description,icon\n"]
        for fc in p.copies:
            if fc.dst.suffix != ".md" or "/agents/" not in str(fc.dst):
                continue
            name = fc.dst.stem
            category = fc.label.split("/")[0] if fc.label and "/" in fc.label else "—"
            desc = self._extract_agent_description(fc.src).replace(",", ";")
            manifest_lines.append(f"{name},{name}.md,{category},{desc},🤖\n")
        p.templates.append(TemplateRender(
            dst=self._target / "_grimoire" / "_config" / "agent-manifest.csv",
            content="".join(manifest_lines),
            label="agent-manifest.csv",
        ))

        # Session branch metadata
        p.templates.append(TemplateRender(
            dst=self._target / "_grimoire-output" / ".runs" / "main" / "branch.json",
            content='{"name": "main", "created": "auto", "active": true}\n',
            label=".runs/main/branch.json",
        ))

    def _plan_agent_wrappers(self, p: ScaffoldPlan) -> None:
        """Generate .github/agents/*.agent.md wrappers for VS Code discovery."""
        gh_agents = self._target / ".github" / "agents"
        concierge_name = "concierge"
        for fc in p.copies:
            if fc.dst.suffix != ".md" or "/agents/" not in str(fc.dst):
                continue
            name = fc.dst.stem
            wrapper_dst = gh_agents / f"{name}.agent.md"
            if wrapper_dst.is_file():
                continue
            desc = self._extract_agent_description(fc.src)
            is_entry = name == concierge_name
            tools = "['read', 'search']" if not is_entry else "['read', 'search', 'execute']"
            lines = [
                "---",
                f"description: '{desc}'",
                f"tools: {tools}",
            ]
            if not is_entry:
                lines.append("user-invocable: false")
            lines.append("---")
            lines.append("")
            lines.append(f"1. Load {{{{project-root}}}}/_grimoire/_config/custom/agents/{name}.md")
            lines.append("2. Follow ALL activation instructions in the agent file")
            lines.append("")
            p.templates.append(TemplateRender(
                dst=wrapper_dst,
                content="\n".join(lines),
                label=f".github/agents/{name}.agent.md",
            ))

    @staticmethod
    def _extract_agent_description(src: Path) -> str:
        """Extract description from internal agent YAML frontmatter."""
        try:
            text = src.read_text(encoding="utf-8")
        except OSError:
            return "Grimoire agent"
        m = re.search(r'^description:\s*["\']?(.+?)["\']?\s*$', text, re.MULTILINE)
        if m:
            return m.group(1).replace("'", "''")
        return "Grimoire agent"

    def _plan_copilot_instructions(self, p: ScaffoldPlan) -> None:
        copilot_file = self._target / ".github" / "copilot-instructions.md"
        if copilot_file.is_file():
            return  # Don't overwrite existing instructions

        # Build enriched agents table with descriptions
        lines = ["| Agent | Role | Description |", "|-------|------|-------------|",]
        for fc in p.copies:
            if fc.dst.suffix != ".md" or "/agents/" not in str(fc.dst):
                continue
            name = fc.dst.stem
            desc = self._extract_agent_description(fc.src)
            category = fc.label.split("/")[0] if fc.label and "/" in fc.label else "—"
            lines.append(f"| {name} | {category} | {desc} |")
        agents_table = "\n".join(lines) if len(lines) > 2 else "(none)"

        v = self._tpl_vars()
        v["agents_table"] = agents_table
        p.templates.append(TemplateRender(
            dst=copilot_file,
            content=Template(_COPILOT_INSTRUCTIONS_TPL).safe_substitute(v),
            label=".github/copilot-instructions.md",
        ))

    def _plan_gitignore(self, p: ScaffoldPlan) -> None:
        """Add grimoire-specific patterns to .gitignore."""
        gitignore = self._target / ".gitignore"
        marker = "# --- Grimoire Kit ---"
        section = (
            f"{marker}\n"
            "# Session runs — ephemeral runtime data\n"
            "_grimoire-output/.runs/\n"
            "# Memory archives — compressed old sessions\n"
            "_grimoire/_memory/archives/\n"
        )

        if gitignore.is_file():
            existing = gitignore.read_text(encoding="utf-8")
            if marker in existing:
                return  # Already has grimoire section
            content = existing.rstrip() + "\n\n" + section
        else:
            content = section

        p.templates.append(TemplateRender(
            dst=gitignore,
            content=content,
            label=".gitignore (grimoire patterns)",
        ))

    @staticmethod
    def _list_planned_agents(p: ScaffoldPlan) -> list[str]:
        """Extract agent labels from planned copies."""
        agents: list[str] = []
        for fc in p.copies:
            if fc.dst.suffix == ".md" and "/agents/" in str(fc.dst):
                agents.append(fc.label or fc.dst.stem)
        return agents
