"""Project scaffolding engine — creates a complete Grimoire project structure.

The engine works in two phases:

1. **Plan** — build a ``ScaffoldPlan`` describing every directory, file copy,
   and template rendering without touching the filesystem.
2. **Execute** — apply the plan atomically (as much as possible).

This separation makes ``--dry-run`` trivial and unit testing straightforward.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from pathlib import Path
from string import Template

from grimoire.archetypes import bundled_path as archetypes_path
from grimoire.core.archetype_resolver import ResolvedArchetype
from grimoire.core.scanner import ScanResult
from grimoire.data import framework_path

# ── Data models ───────────────────────────────────────────────────────────────


@dataclass
class FileCopy:
    """A file to copy from *src* to *dst*."""

    src: Path
    dst: Path
    label: str = ""


@dataclass
class TemplateRender:
    """A template file to render with *variables* and write to *dst*."""

    dst: Path
    content: str
    label: str = ""


@dataclass
class ScaffoldPlan:
    """Everything the scaffolder intends to do — inspectable before execution."""

    directories: list[Path] = field(default_factory=list)
    copies: list[FileCopy] = field(default_factory=list)
    templates: list[TemplateRender] = field(default_factory=list)

    @property
    def total_operations(self) -> int:
        return len(self.directories) + len(self.copies) + len(self.templates)


@dataclass
class ScaffoldResult:
    """Outcome of executing a plan."""

    created_dirs: list[str] = field(default_factory=list)
    copied_files: list[str] = field(default_factory=list)
    rendered_files: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def total(self) -> int:
        return len(self.created_dirs) + len(self.copied_files) + len(self.rendered_files)


# ── Templates ─────────────────────────────────────────────────────────────────

_PROJECT_CONTEXT_TPL = """\
# Grimoire Kit — Project Context
# Auto-generated by: grimoire init
# Run: grimoire doctor  to validate this file.

project:
  name: "$project_name"
  description: ""
  type: "$project_type"
  stack: [$stack_list]
  repos:
    - name: "$project_name"
      path: "."
      default_branch: "main"

user:
  name: "$user_name"
  language: "$language"
  skill_level: "$skill_level"

memory:
  backend: "$backend"

agents:
  archetype: "$archetype"
  custom_agents: []

installed_archetypes:
  - "$archetype"
"""

_MEMORY_CONFIG_TPL = """\
# Grimoire Memory Configuration — auto-generated
user_name: "$user_name"
communication_language: "$language"
document_output_language: "$language"
"""

_SHARED_CONTEXT_DEFAULT = """\
# Shared Context — Project Awareness
# This file is loaded by agents to understand your project.

## Project
- **Name**: $project_name
- **Type**: $project_type
- **Stack**: $stack_list

## Conventions
- Communication language: $language

## Key Decisions
(none yet — decisions will be logged here as the project evolves)
"""

_DECISIONS_LOG = """\
# Decisions Log
# Append decisions as they are made during the project.
"""

_MANIFEST_HEADER = "name,file,role,icon\n"


# ── Scaffolder ────────────────────────────────────────────────────────────────


class ProjectScaffolder:
    """Build and execute a scaffold plan for a Grimoire project."""

    def __init__(
        self,
        target: Path,
        *,
        project_name: str,
        user_name: str,
        language: str,
        skill_level: str,
        scan: ScanResult | None,
        resolved: ResolvedArchetype,
        backend: str,
    ) -> None:
        self._target = target.resolve()
        self._project_name = project_name
        self._user_name = user_name
        self._language = language
        self._skill_level = skill_level
        self._scan = scan
        self._resolved = resolved
        self._backend = backend
        self._archetypes = archetypes_path()
        self._framework = framework_path()

    # ── Public API ────────────────────────────────────────────────────

    def plan(self) -> ScaffoldPlan:
        """Build a complete scaffold plan without touching the filesystem."""
        p = ScaffoldPlan()
        self._plan_directories(p)
        self._plan_meta_agents(p)
        self._plan_archetype_agents(p)
        self._plan_stack_agents(p)
        self._plan_feature_agents(p)
        self._plan_framework(p)
        self._plan_templates(p)
        return p

    def execute(self, plan: ScaffoldPlan) -> ScaffoldResult:
        """Execute a scaffold plan, writing to the filesystem."""
        result = ScaffoldResult()

        for d in plan.directories:
            d.mkdir(parents=True, exist_ok=True)
            result.created_dirs.append(str(d.relative_to(self._target)))

        for fc in plan.copies:
            fc.dst.parent.mkdir(parents=True, exist_ok=True)
            if fc.src.is_dir():
                shutil.copytree(fc.src, fc.dst, dirs_exist_ok=True)
            else:
                shutil.copy2(fc.src, fc.dst)
            result.copied_files.append(fc.label or str(fc.dst.relative_to(self._target)))

        for tr in plan.templates:
            tr.dst.parent.mkdir(parents=True, exist_ok=True)
            tr.dst.write_text(tr.content, encoding="utf-8")
            result.rendered_files.append(tr.label or str(tr.dst.relative_to(self._target)))

        return result

    # ── Planning helpers ──────────────────────────────────────────────

    def _agents_dir(self) -> Path:
        return self._target / "_grimoire" / "_config" / "custom" / "agents"

    def _memory_dir(self) -> Path:
        return self._target / "_grimoire" / "_memory"

    def _tpl_vars(self) -> dict[str, str]:
        stacks = [d.name for d in self._scan.stacks] if self._scan else []
        stack_list = ", ".join(f'"{s}"' for s in stacks) if stacks else ""
        return {
            "project_name": self._project_name,
            "user_name": self._user_name,
            "language": self._language,
            "skill_level": self._skill_level,
            "project_type": self._scan.project_type if self._scan else "generic",
            "stack_list": stack_list,
            "archetype": self._resolved.archetype,
            "backend": self._backend,
        }

    def _plan_directories(self, p: ScaffoldPlan) -> None:
        base = self._target
        dirs = [
            base / "_grimoire" / "_config" / "custom" / "agents",
            base / "_grimoire" / "_config" / "custom" / "prompt-templates",
            base / "_grimoire" / "_config" / "custom" / "workflows",
            base / "_grimoire" / "_memory" / "agent-learnings",
            base / "_grimoire" / "_memory" / "session-summaries",
            base / "_grimoire" / "_memory" / "archives",
            base / "_grimoire-output" / ".runs" / "main",
            base / "_grimoire-output" / "team-vision",
            base / "_grimoire-output" / "team-build" / "stories",
            base / "_grimoire-output" / "team-build" / "test-reports",
            base / "_grimoire-output" / "team-ops",
            base / "_grimoire-output" / "contracts",
        ]
        p.directories.extend(dirs)

    def _plan_meta_agents(self, p: ScaffoldPlan) -> None:
        meta_dir = self._archetypes / "meta" / "agents"
        if not meta_dir.is_dir():
            return
        agents_dst = self._agents_dir()
        for md in sorted(meta_dir.glob("*.md")):
            p.copies.append(FileCopy(
                src=md,
                dst=agents_dst / md.name,
                label=f"meta/{md.stem}",
            ))

    def _plan_archetype_agents(self, p: ScaffoldPlan) -> None:
        arch = self._resolved.archetype
        arch_dir = self._archetypes / arch
        if not arch_dir.is_dir():
            return

        # Agents
        agents_src = arch_dir / "agents"
        if agents_src.is_dir():
            agents_dst = self._agents_dir()
            for md in sorted(agents_src.glob("*.md")):
                p.copies.append(FileCopy(
                    src=md,
                    dst=agents_dst / md.name,
                    label=f"{arch}/{md.stem}",
                ))

        # Shared context template (prefer archetype-specific over default)
        shared_tpl = arch_dir / "shared-context.tpl.md"
        if shared_tpl.is_file():
            content = shared_tpl.read_text(encoding="utf-8")
            # Substitute known variables using safe_substitute
            rendered = Template(content).safe_substitute(self._tpl_vars())
            p.templates.append(TemplateRender(
                dst=self._memory_dir() / "shared-context.md",
                content=rendered,
                label="shared-context.md (archetype)",
            ))

    def _plan_stack_agents(self, p: ScaffoldPlan) -> None:
        stack_agents_dir = self._archetypes / "stack" / "agents"
        if not stack_agents_dir.is_dir():
            return
        agents_dst = self._agents_dir()
        for agent_name in self._resolved.stack_agents:
            md = stack_agents_dir / f"{agent_name}.md"
            if md.is_file():
                p.copies.append(FileCopy(
                    src=md,
                    dst=agents_dst / md.name,
                    label=f"stack/{agent_name}",
                ))

    def _plan_feature_agents(self, p: ScaffoldPlan) -> None:
        agents_dst = self._agents_dir()
        for agent_name in self._resolved.feature_agents:
            # Known feature agent paths
            if agent_name == "vectus":
                src = self._archetypes / "features" / "vector-memory" / "vectus.md"
                if src.is_file():
                    p.copies.append(FileCopy(
                        src=src,
                        dst=agents_dst / "vectus.md",
                        label="feature/vectus",
                    ))

    def _plan_framework(self, p: ScaffoldPlan) -> None:
        fw = self._framework
        dst_custom = self._target / "_grimoire" / "_config" / "custom"

        # Core framework files
        for name in ("agent-base.md", "agent-base-compact.md"):
            src = fw / name
            if src.is_file():
                p.copies.append(FileCopy(src=src, dst=dst_custom / name, label=f"framework/{name}"))

        # Shell scripts
        for name in ("cc-verify.sh", "sil-collect.sh"):
            src = fw / name
            if src.is_file():
                p.copies.append(FileCopy(src=src, dst=dst_custom / name, label=f"framework/{name}"))

        # Prompt templates
        pt_src = fw / "prompt-templates"
        if pt_src.is_dir():
            p.copies.append(FileCopy(
                src=pt_src,
                dst=dst_custom / "prompt-templates",
                label="framework/prompt-templates/",
            ))

        # Workflows
        wf_src = fw / "workflows"
        if wf_src.is_dir():
            p.copies.append(FileCopy(
                src=wf_src,
                dst=dst_custom / "workflows",
                label="framework/workflows/",
            ))

        # Memory system
        mem_dst = self._memory_dir()
        for name in ("maintenance.py", "session-save.py"):
            src = fw / "memory" / name
            if src.is_file():
                p.copies.append(FileCopy(src=src, dst=mem_dst / name, label=f"memory/{name}"))

        backends_src = fw / "memory" / "backends"
        if backends_src.is_dir():
            p.copies.append(FileCopy(
                src=backends_src,
                dst=mem_dst / "backends",
                label="memory/backends/",
            ))

        # Memory templates
        for tpl_name in ("contradiction-log.tpl.md", "failure-museum.tpl.md"):
            src = fw / "memory" / tpl_name
            if src.is_file():
                dst_name = tpl_name.replace(".tpl", "")
                p.copies.append(FileCopy(src=src, dst=mem_dst / dst_name, label=f"memory/{dst_name}"))

    def _plan_templates(self, p: ScaffoldPlan) -> None:
        v = self._tpl_vars()

        # project-context.yaml
        p.templates.append(TemplateRender(
            dst=self._target / "project-context.yaml",
            content=Template(_PROJECT_CONTEXT_TPL).safe_substitute(v),
            label="project-context.yaml",
        ))

        # Memory config
        p.templates.append(TemplateRender(
            dst=self._memory_dir() / "config.yaml",
            content=Template(_MEMORY_CONFIG_TPL).safe_substitute(v),
            label="_grimoire/_memory/config.yaml",
        ))

        # Shared context (only if archetype didn't provide one)
        shared_dst = self._memory_dir() / "shared-context.md"
        if not any(t.dst == shared_dst for t in p.templates):
            p.templates.append(TemplateRender(
                dst=shared_dst,
                content=Template(_SHARED_CONTEXT_DEFAULT).safe_substitute(v),
                label="shared-context.md (default)",
            ))

        # Decisions log
        p.templates.append(TemplateRender(
            dst=self._memory_dir() / "decisions-log.md",
            content=_DECISIONS_LOG,
            label="decisions-log.md",
        ))

        # Session state
        p.templates.append(TemplateRender(
            dst=self._memory_dir() / "session-state.md",
            content="# Session State\n\nstatus: idle\n",
            label="session-state.md",
        ))

        # Agent manifest
        manifest_lines = [_MANIFEST_HEADER]
        all_agents = list(self._list_planned_agents(p))
        for agent_label in all_agents:
            parts = agent_label.split("/")
            name = parts[-1] if len(parts) > 1 else parts[0]
            manifest_lines.append(f"{name},{name}.md,agent,🤖\n")
        p.templates.append(TemplateRender(
            dst=self._target / "_grimoire" / "_config" / "agent-manifest.csv",
            content="".join(manifest_lines),
            label="agent-manifest.csv",
        ))

        # Session branch metadata
        p.templates.append(TemplateRender(
            dst=self._target / "_grimoire-output" / ".runs" / "main" / "branch.json",
            content='{"name": "main", "created": "auto", "active": true}\n',
            label=".runs/main/branch.json",
        ))

    @staticmethod
    def _list_planned_agents(p: ScaffoldPlan) -> list[str]:
        """Extract agent labels from planned copies."""
        agents: list[str] = []
        for fc in p.copies:
            if fc.dst.suffix == ".md" and "/agents/" in str(fc.dst):
                agents.append(fc.label or fc.dst.stem)
        return agents
