"""Grimoire registry — agent and module distribution."""

from grimoire.registry.agents import AgentDef, AgentRegistry, ArchetypeDNA
from grimoire.registry.discovery import discover_backends, discover_tools
from grimoire.registry.local import LocalRegistry, RegistryItem
from grimoire.registry.packs import (
    PackCompatibility,
    PackCompatibilityCore,
    PackComponent,
    PackDistributionReport,
    PackGateDecision,
    PackInstallDryRun,
    PackInstallDryRunChange,
    PackInstallDryRunDiff,
    PackInstallDryRunItem,
    PackManifest,
    PackMarketplaceCatalog,
    PackMarketplaceCompatibility,
    PackMarketplaceEntry,
    PackMarketplacePublication,
    PackMarketplaceSummary,
    PackMetadata,
    PackOperatorPackEntry,
    PackOperatorPolicyEntry,
    PackOperatorSummary,
    PackOperatorView,
    PackOverlay,
    PackPolicy,
    PackRegistry,
    PackRequirement,
    PackResolution,
    PackResolutionComponent,
    PackResolutionOverlay,
    PackResolutionPack,
    PackResolutionPolicy,
    PackResolutionRequirement,
    PackResolutionTest,
    PackTest,
    PackValidationIssue,
    PackValidationReport,
)

__all__ = [
    "AgentDef",
    "AgentRegistry",
    "ArchetypeDNA",
    "LocalRegistry",
    "PackCompatibility",
    "PackCompatibilityCore",
    "PackComponent",
    "PackDistributionReport",
    "PackGateDecision",
    "PackInstallDryRun",
    "PackInstallDryRunChange",
    "PackInstallDryRunDiff",
    "PackInstallDryRunItem",
    "PackManifest",
    "PackMarketplaceCatalog",
    "PackMarketplaceCompatibility",
    "PackMarketplaceEntry",
    "PackMarketplacePublication",
    "PackMarketplaceSummary",
    "PackMetadata",
    "PackOperatorPackEntry",
    "PackOperatorPolicyEntry",
    "PackOperatorSummary",
    "PackOperatorView",
    "PackOverlay",
    "PackPolicy",
    "PackRegistry",
    "PackRequirement",
    "PackResolution",
    "PackResolutionComponent",
    "PackResolutionOverlay",
    "PackResolutionPack",
    "PackResolutionPolicy",
    "PackResolutionRequirement",
    "PackResolutionTest",
    "PackTest",
    "PackValidationIssue",
    "PackValidationReport",
    "RegistryItem",
    "discover_backends",
    "discover_tools",
]
