"""Identity propagation into ``.github/copilot-instructions.md``.

The file is regenerated by the kit and then patched with the project's identity,
so the patcher has to survive fields the project left empty.
"""

from __future__ import annotations

from pathlib import Path

from grimoire.cli.cmd_setup import UserValues, _apply_copilot


class TestEmptyValueDoesNotEatTheNextLine:
    """An empty field must blank its own line, not the following one.

    ``\\s*`` in the field patterns matched across the newline, so an empty
    value consumed the line break and overwrote the next field — turning one
    unset name into a lost language setting. It only became reachable once the
    kit regenerated the file with fields the project had left unset, and it
    made ``up`` and identity propagation fight over the file on every run.
    """

    def test_empty_user_name_preserves_the_next_field(self, tmp_path: Path) -> None:
        ci = tmp_path / "copilot-instructions.md"
        ci.write_text(
            "- **Project**: demo\n- **User**: \n- **Language**: Français\n",
            encoding="utf-8",
        )
        _apply_copilot(ci, UserValues(project_name="demo", user_name=""))
        assert "- **Language**: Français" in ci.read_text(encoding="utf-8")

    def test_populated_value_is_still_replaced(self, tmp_path: Path) -> None:
        ci = tmp_path / "copilot-instructions.md"
        ci.write_text("- **User**: old\n- **Language**: Français\n", encoding="utf-8")
        _apply_copilot(ci, UserValues(user_name="Guilhem"))
        text = ci.read_text(encoding="utf-8")
        assert "- **User**: Guilhem" in text
        assert "- **Language**: Français" in text

    def test_applying_the_same_values_twice_is_a_no_op(self, tmp_path: Path) -> None:
        ci = tmp_path / "copilot-instructions.md"
        ci.write_text("- **User**: Guilhem\n- **Language**: Français\n", encoding="utf-8")
        vals = UserValues(user_name="Guilhem")
        _apply_copilot(ci, vals)
        assert _apply_copilot(ci, vals) is False
