"""Anti-drift guard: extensions/README.md table mirrors the manifests.

The "Extensions disponibles" table historically was hand-maintained and
listed 6 of 8 extensions (grimoire-mcp and fennara-godot were missing).
It is now generated by ``scripts/gen-extensions-table.py`` from the
``extension.json`` manifests; this test fails closed whenever a manifest
is added, removed, or reworded without regenerating the table.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GENERATOR = ROOT / "scripts" / "gen-extensions-table.py"
README = ROOT / "extensions" / "README.md"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_extensions_table", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_readme_table_matches_manifests() -> None:
    gen = _load_generator()
    content = README.read_text(encoding="utf-8")
    assert gen.apply(content) == content, (
        "extensions/README.md is out of sync with the extension.json manifests "
        "— run: python scripts/gen-extensions-table.py"
    )


def test_every_manifest_row_is_present() -> None:
    content = README.read_text(encoding="utf-8")
    manifests = sorted((ROOT / "extensions").glob("*/extension.json"))
    assert manifests, "no extension manifests found"
    for manifest_path in manifests:
        ext_id = json.loads(manifest_path.read_text(encoding="utf-8"))["id"]
        assert f"[{ext_id}]({ext_id}/extension.json)" in content, (
            f"extension {ext_id!r} missing from extensions/README.md table"
        )
